// Korean for every string the plugin shows; English is the key. Terrain names come from the editor as they are.
// `tests/ko.test.ts` fails on a `t("…")` or `msg("…")` in the source with no entry here, and on an entry nothing uses.
export const KO: Record<string, string> = {
  " · adjusted": " · 보정됨",
  ", ISOM updated": ", ISOM 갱신됨",
  ", {n} left as they are": ", {n}칸은 그대로",
  "Adaptive colour": "적응형 색상",
  "Adjust": "보정",
  "All": "전체",
  "Apply": "적용",
  "Auto-levels": "자동 레벨",
  "Back to every terrain's own tile colour": "모든 지형을 자기 타일 색으로 되돌립니다",
  "Blur": "흐림",
  "Brightness": "밝기",
  "Brightness bands (heightmap)": "밝기 구간 (높이 맵)",
  "Cancel": "취소",
  "Choose File…": "파일 선택…",
  "Choose an image first.": "먼저 이미지를 고르세요.",
  "Choose an image to preview.": "이미지를 고르면 미리 봅니다.",
  "Clean up": "정리",
  "Close this dialog, drag the target rectangle on the map, and come back here with it selected": "이 대화 상자를 닫고 맵에서 대상 사각형을 드래그한 뒤, 그 영역을 고른 채로 돌아옵니다",
  "Contrast": "대비",
  "Despeckle": "잡티 제거",
  "Exact key colours": "정확한 기준 색",
  "Eyedropper: click a spot on the source preview to make it the key colour of {name}": "스포이트: 원본 미리보기의 한 곳을 클릭하면 {name}의 기준 색이 됩니다",
  "Fetch the picture at this address": "이 주소의 그림을 가져옵니다",
  "Fill the area (crop)": "영역 채우기 (잘라 냄)",
  "Fit": "맞춤",
  "Fit inside (letterbox)": "안에 맞추기 (여백)",
  "Flat tiles": "평지 타일",
  "Flip": "뒤집기",
  "Gamma": "감마",
  "Height": "세로",
  "Horizontally ↔": "좌우 ↔",
  "Hue": "색조",
  "Hue and relative brightness, with the picture's range fitted to the terrains' — good for photos and drawings as they are.": "색조와 상대 밝기로 맞추며, 그림의 범위를 지형의 범위에 맞춥니다. 사진이나 그림을 그대로 쓸 때 좋습니다.",
  "Image": "이미지",
  "Image URL": "이미지 URL",
  "Invert": "반전",
  "Isometric terrain": "아이소메트릭 지형",
  "Key colour for {name}": "{name}의 기준 색",
  "Key colour {name} matches in the picture (its own tiles average {colour})": "그림에서 {name}{name|으로} 맞출 기준 색 (자기 타일의 평균은 {colour})",
  "Left": "왼쪽",
  "Load": "불러오기",
  "Loading the tileset…": "타일셋을 불러오는 중…",
  "Loading…": "불러오는 중…",
  "Marked area ({width} × {height} at {x}, {y})": "표시한 영역 ({x}, {y} 위치의 {width} × {height})",
  "Match": "맞추기",
  "Match by": "맞추는 방식",
  "Method": "방식",
  "Minimum region size": "최소 영역 크기",
  "Nearest (pixel art, one pixel per tile)": "최근접 (픽셀 아트, 픽셀 하나에 타일 하나)",
  "No picture on the clipboard that the page may read — press Ctrl+V in this dialog instead.": "페이지가 읽을 수 있는 그림이 클립보드에 없습니다. 대신 이 대화 상자에서 Ctrl+V를 누르세요.",
  "No terrain types — the tileset graphics are not installed.": "지형 종류가 없습니다. 타일셋 그래픽이 설치되어 있지 않습니다.",
  "None": "없음",
  "Open or create a map first.": "먼저 맵을 열거나 만드세요.",
  "Paint as": "칠하는 방식",
  "Paint every lattice diamond with the isometric brush: cliffs and shorelines are generated at the boundaries": "격자의 모든 마름모를 아이소메트릭 브러시로 칠합니다. 경계에는 절벽과 해안선이 만들어집니다",
  "Paint into": "칠할 곳",
  "Paste": "붙여넣기",
  "Pick key colour for {name} from the picture": "그림에서 {name}의 기준 색 고르기",
  "Pick on Map…": "맵에서 고르기…",
  "Picture": "그림",
  "Plain colour distance to the key colours — set them with the swatches or the eyedropper.": "기준 색과의 단순한 색 거리로 맞춥니다. 기준 색은 색상 칸이나 스포이트로 정하세요.",
  "Rectangle": "사각형",
  "Regions with fewer cells than this join their commonest neighbour": "칸 수가 이보다 적은 영역은 가장 흔한 이웃에 합쳐집니다",
  "Reset": "초기화",
  "Reset colours": "색 초기화",
  "Result": "결과",
  "Sampling": "샘플링",
  "Saturation": "채도",
  "Smooth (photos)": "부드럽게 (사진)",
  "Source (adjusted)": "원본 (보정됨)",
  "Stamp flat tile pairs only; the ISOM is left alone (Rebuild ISOM from Tiles afterwards to use the isometric brush)": "평지 타일 쌍만 찍고 ISOM은 건드리지 않습니다 (아이소메트릭 브러시를 쓰려면 나중에 타일에서 ISOM 다시 만들기를 하세요)",
  "Stretch the picture's darkest and brightest to black and white first": "먼저 그림의 가장 어두운 곳과 밝은 곳을 검정과 흰색까지 늘립니다",
  "Stretch to the area": "영역에 맞게 늘이기",
  "Take the picture on the system clipboard (Ctrl+V works too)": "시스템 클립보드의 그림을 가져옵니다 (Ctrl+V도 됩니다)",
  "Target": "대상",
  "Target area": "대상 영역",
  "Terrain from Image": "이미지로 지형 만들기",
  "Terrain from Image into Area…": "영역에 이미지로 지형 만들기…",
  "Terrain from Image into Marked Area…": "표시한 영역에 이미지로 지형 만들기…",
  "Terrain from Image — {name}": "이미지로 지형 만들기 — {name}",
  "Terrain from Image: drag the target rectangle": "이미지로 지형 만들기: 대상 사각형을 드래그하세요",
  "Terrain from Image…": "이미지로 지형 만들기…",
  "Terrain from image ({name})": "이미지로 지형 만들기 ({name})",
  "Terrains": "지형",
  "Terrains to use": "사용할 지형",
  "That cell is transparent — pick a painted one.": "그 칸은 투명합니다. 칠해진 칸을 고르세요.",
  "The picture as the matcher sees it — with the eyedropper armed, click to take a key colour": "맞추기가 보는 그대로의 그림입니다. 스포이트를 켠 상태에서 클릭하면 기준 색을 가져옵니다",
  "The target rectangle is empty.": "대상 사각형이 비어 있습니다.",
  "The tileset could not be loaded: {error}": "타일셋을 불러올 수 없습니다: {error}",
  "Ticked terrains, top to bottom, become bands from the picture's darkest to its brightest.": "체크한 지형이 위에서 아래 순서로, 그림의 가장 어두운 곳부터 가장 밝은 곳까지의 구간이 됩니다.",
  "Top": "위",
  "Use {name}": "{name} 사용",
  "Vertically ↕": "상하 ↕",
  "Weigh": "비중",
  "Whole map ({width} × {height})": "맵 전체 ({width} × {height})",
  "Width": "가로",
  "blur": "흐림",
  "despeckle": "잡티 제거",
  "drag the rectangle on the map": "맵에서 사각형을 드래그",
  "even": "같음",
  "hue {n}": "색조 {n}",
  "image": "이미지",
  "light {n}": "밝기 {n}",
  "min. region": "최소 영역",
  "no image yet": "아직 이미지 없음",
  "off": "끔",
  "pasted image": "붙여넣은 이미지",
  "picture": "그림",
  "{n, plural, one {# diamond} other {# diamonds}} could not take their terrain": "마름모 {n}개에 지형을 칠할 수 없었습니다",
  "{name} — height {height}": "{name} — 높이 {height}",
  "{name} — height {height}, buildable": "{name} — 높이 {height}, 건설 가능",
  "{what} — nothing changed": "{what} — 바뀐 것 없음",
  "{what} — {n, plural, one {# tile} other {# tiles}}": "{what} — 타일 {n}개",
  "{width} × {height} cells at {x}, {y} — {painted} painted, {n, plural, one {# terrain} other {# terrains}}": "{x}, {y} 위치의 {width} × {height}칸 — {painted}칸 칠함, 지형 {n}개",
  "— this map has no ISOM section": "— 이 맵에는 ISOM 섹션이 없습니다",
  "…or drop a picture on this dialog, or press Ctrl+V": "…또는 이 대화 상자에 그림을 끌어다 놓거나 Ctrl+V를 누르세요",
};
